studentmanagement/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('students.urls'))
]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
   path('', views.index, name='index'),
   path('add/', views.add, name='add'),
   path('edit/<int:id>/', views.edit, name='edit'),
   path('delete/<int:id>/', views.delete, name='delete'),
]

students/models.py
from django.db import models

class Students(models.Model):
    student_number=models.PositiveIntegerField()
    first_name=models.CharField(max_length=200)
    last_name=models.CharField(max_length=200)
    email=models.EmailField(max_length=200)
    field_to_study=models.CharField(max_length=200)
    percentage=models.FloatField()

    def __str__(self):
        return f'Students:{self.first_name} {self.last_name}'

students/forms.py
from django import forms
from .models import Students


class StudentForm(forms.ModelForm):
  class Meta:
    model = Students
    fields = "__all__"
    labels = {
      'student_number': 'Student Number',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'email': 'Email',
      'field_to_study': 'Field of Study',
      'gpa': 'Percentage'
    }
    widgets = {
      'student_number': forms.NumberInput(attrs={'class': 'form-control'}),
      'first_name': forms.TextInput(attrs={'class': 'form-control'}),
      'last_name': forms.TextInput(attrs={'class': 'form-control'}),
      'email': forms.EmailInput(attrs={'class': 'form-control'}),
      'field_to_study': forms.TextInput(attrs={'class': 'form-control'}),
      'percentage': forms.NumberInput(attrs={'class': 'form-control'}),
    }

students/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Students
from .forms import StudentForm



def index(request):
    students = Students.objects.all()
    return render(request, 'index.html', {'students': students})


def add(request):
    if request.method == 'POST':
        form = StudentForm(request.POST)
        if form.is_valid():
            new_student = Students(
                student_number=form.cleaned_data['student_number'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
                field_to_study=form.cleaned_data['field_to_study'],
                percentage=form.cleaned_data['percentage']
            )
            new_student.save()
            return render(request, 'add.html', {
                'form': StudentForm(),
                'success': True
            })
    else:
        form = StudentForm()

    return render(request, 'add.html', {
        'form': form
    })

def edit(request, id):
  if request.method == 'POST':
    student = Students.objects.get(pk=id)
    form = StudentForm(request.POST, instance=student)
    if form.is_valid():
      form.save()
      return render(request, 'edit.html', {
        'form': form,
        'success': True
      })
  else:
    student = Students.objects.get(pk=id)
    form = StudentForm(instance=student)
  return render(request, 'edit.html', {
    'form': form
  })


def delete(request, id):
    if request.method == 'POST':
        try:
            student = Students.objects.get(pk=id)
            student.delete()
        except Students.DoesNotExist:
            # Optionally, add a message or log the error
            pass
    return HttpResponseRedirect(reverse('students:index'))

templates/add.html
{% extends "base.html" %}

{% block body %}
  <h3 class="text-center m-4">Add Student</h3>
  {% if success %}
    <div class="alert alert-success" role="alert">
      The new student added successfully.
      <a href="{% url 'students:index' %}" class="alert-link">Go to Home Page.</a>
    </div>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-6">
        <div class="card bg-light mb-3">
          <div class="card-header">
            <i class="fa-solid fa-address-card fa-lg"></i> Student Registration
          </div>
          <div class="card-body">
            <form action="{% url 'students:add' %}" method="POST">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Add</button>
              <a href="{% url 'students:index' %}" class="btn btn-secondary">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Student Management System</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'students:index' %}">
          <i class="fa-solid fa-graduation-cap fa-lg"></i> Student Management System
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'students:index' %}">
                <i class="fa-solid fa-list fa-lg"></i> All Students
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'students:add' %}">
                <i class="fa-solid fa-plus fa-lg"></i> Add Student
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      {% block body %}
      {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/edit.html
<!--edit page-->
{% extends "base.html" %}


{% block body %}
  <h3 class="text-center m-4">Update Student</h3>
  {% if success %}
    <div class="alert alert-success" role="alert">
      The student updated successfully.
      <a href="{% url 'students:index' %}" class="alert-link">Go to Home Page.</a>
    </div>
  {% else %}
    <div class="row justify-content-center">
      <div class="col-6">
        <div class="card bg-light mb-3">
          <div class="card-header">
            <i class="fa-solid fa-pen-to-square fa-lg"></i> Update Student Records
          </div>
          <div class="card-body">
            <form action="" method="POST">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-primary">Update</button>
              <a href="{% url 'students:index' %}" class="btn btn-secondary">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block body %}
<h3 class="m-4">All Students</h3>
<div class="row">
  <div class="col-12">
    {% if students %}
    <div class="card bg-light ms-4 me-4 mb-4">
      <div class="card-header">
        <i class="fa-solid fa-list fa-lg"></i> Student Records
      </div>
      <div class="card-body">
        <p class="card-text">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Student Number</th>
                  <th scope="col">First Name</th>
                  <th scope="col">Last Name</th>
                  <th scope="col">Email</th>
                  <th scope="col">Field of Study</th>
                  <th scope="col">GPA</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for student in students %}
                  <tr>
                    <td>{{ student.student_number }}</td>
                    <td>{{ student.first_name }}</td>
                    <td>{{ student.last_name }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.field_to_study }}</td>
                    <td>{{ student.percentage }}</td>
                    <td>
                      <button type="button" class="btn btn-success me-1" href="" data-bs-toggle="modal" data-bs-target="#myModal{{student.id}}">
                        <i class="fa-solid fa-circle-info fa-lg"></i>
                      </button>

                      <!-- Modal - View Student -->
                      <div class="modal" id="myModal{{student.id}}" tabindex="-1" aria-labelledby="myModalLabel1" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title">
                                Student: {{ student.first_name }} {{ student.last_name }}
                              </h5>

                            </div>
                            <div class="modal-body">
                              <ul class="list-unstyled">
                                <li>Student Number: <strong>{{ student.student_number }}</strong></li>
                                <li>First Name: <strong>{{ student.first_name }}</strong></li>
                                <li>Last Name: <strong>{{ student.last_name }}</strong></li>
                                <li>Email: <strong>{{ student.email }}</strong></li>
                                <li>Field of Study: <strong>{{ student.field_to_study }}</strong></li>
                                <li>GPA: <strong>{{ student.percentage }}</strong></li>
                              </ul>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                            </div>
                          </div>
                        </div>
                      </div>

                      <a class="btn btn-warning me-1" href="{% url 'students:edit' student.id %}">
                        <i class="fa-solid fa-pen-to-square fa-lg"></i>
                      </a>

                      <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{student.id}}">
                        <i class="fa-solid fa-trash-can fa-lg"></i>
                      </button>

                      <!-- Modal - Delete Student -->
                      <div class="modal" id="delete{{student.id}}" tabindex="-1" aria-labelledby="myModalLabel2" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title">
                                Student: {{ student.first_name }} {{ student.last_name }}
                              </h5>

                            </div>
                            <div class="modal-body">
                              <p>Are you sure you want to delete this student?</p>
                            </div>
                            <div class="modal-footer">
                             <form action="{% url 'students:delete' student.id %}" method="POST">
                                  {% csrf_token %}
                                  <input type="submit" class="btn btn-primary" value="Delete">
                              </form>

                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </p>
      </div>
    </div>
    {% else %}
      <h5 class="alert alert-primary ms-4 me-4">No Student Records</h5>
    {% endif %}
  </div>
</div>
{% endblock %}